import type { Business, User, Review, Photo, Recommendation, ExperimentMetrics } from "./types"

// Mock de usuarios
// IDs disponibles para login: user_001, user_002, user_003
export const mockUsers: User[] = [
  {
    user_id: "user_001",
    name: "Ana García",
    review_count: 42,
    yelping_since: "2015-04-10",
    friends: ["user_002", "user_003"],
    useful: 120,
    funny: 35,
    cool: 75,
    fans: 12,
    elite: ["2018", "2019", "2020"],
    average_stars: 4.2,
  },
  {
    user_id: "user_002",
    name: "Carlos Rodríguez",
    review_count: 87,
    yelping_since: "2016-08-22",
    friends: ["user_001", "user_003"],
    useful: 230,
    funny: 65,
    cool: 110,
    fans: 24,
    elite: ["2017", "2018", "2019", "2020", "2021"],
    average_stars: 3.8,
  },
  {
    user_id: "user_003",
    name: "María López",
    review_count: 23,
    yelping_since: "2019-01-15",
    friends: ["user_001", "user_002"],
    useful: 45,
    funny: 12,
    cool: 28,
    fans: 5,
    elite: [],
    average_stars: 4.5,
  },
]

// Mock de fotos
const mockPhotos: Photo[] = [
  {
    photo_id: "photo_001",
    business_id: "business_001",
    caption: "Fachada del restaurante",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_002",
    business_id: "business_001",
    caption: "Plato principal",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_003",
    business_id: "business_002",
    caption: "Interior del café",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_004",
    business_id: "business_002",
    caption: "Especialidad de la casa",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_005",
    business_id: "business_003",
    caption: "Área de trabajo",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_006",
    business_id: "business_003",
    caption: "Sala de reuniones",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_007",
    business_id: "business_004",
    caption: "Entrada principal",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_008",
    business_id: "business_004",
    caption: "Habitación estándar",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_009",
    business_id: "business_005",
    caption: "Zona de ejercicios",
    url: "/placeholder.svg?height=400&width=600",
  },
  {
    photo_id: "photo_010",
    business_id: "business_005",
    caption: "Piscina",
    url: "/placeholder.svg?height=400&width=600",
  },
]

// Mock de negocios
export const mockBusinesses: Business[] = [
  {
    business_id: "business_001",
    name: "El Rincón Gourmet",
    address: "Calle Principal 123",
    city: "Madrid",
    state: "MD",
    postal_code: "28001",
    latitude: 40.4168,
    longitude: -3.7038,
    stars: 4.5,
    review_count: 128,
    is_open: 1,
    attributes: {
      RestaurantsPriceRange2: "3",
      BusinessAcceptsCreditCards: true,
      BikeParking: true,
      GoodForKids: true,
    },
    categories: ["Restaurantes", "Español", "Tapas"],
    hours: {
      Monday: "12:00-23:00",
      Tuesday: "12:00-23:00",
      Wednesday: "12:00-23:00",
      Thursday: "12:00-23:00",
      Friday: "12:00-00:00",
      Saturday: "12:00-00:00",
      Sunday: "12:00-22:00",
    },
    photos: mockPhotos.filter((p) => p.business_id === "business_001"),
  },
  {
    business_id: "business_002",
    name: "Café del Arte",
    address: "Avenida Central 45",
    city: "Barcelona",
    state: "CT",
    postal_code: "08001",
    latitude: 41.3851,
    longitude: 2.1734,
    stars: 4.2,
    review_count: 87,
    is_open: 1,
    attributes: {
      RestaurantsPriceRange2: "2",
      WiFi: "free",
      OutdoorSeating: true,
    },
    categories: ["Cafeterías", "Desayuno", "Brunch"],
    hours: {
      Monday: "08:00-20:00",
      Tuesday: "08:00-20:00",
      Wednesday: "08:00-20:00",
      Thursday: "08:00-20:00",
      Friday: "08:00-22:00",
      Saturday: "09:00-22:00",
      Sunday: "09:00-18:00",
    },
    photos: mockPhotos.filter((p) => p.business_id === "business_002"),
  },
  {
    business_id: "business_003",
    name: "Espacio Coworking Innovación",
    address: "Calle Tecnología 78",
    city: "Valencia",
    state: "VC",
    postal_code: "46001",
    latitude: 39.4699,
    longitude: -0.3763,
    stars: 4.7,
    review_count: 45,
    is_open: 1,
    attributes: {
      BusinessAcceptsCreditCards: true,
      WiFi: "free",
      BikeParking: true,
    },
    categories: ["Espacios de Trabajo", "Oficinas", "Servicios Empresariales"],
    hours: {
      Monday: "09:00-21:00",
      Tuesday: "09:00-21:00",
      Wednesday: "09:00-21:00",
      Thursday: "09:00-21:00",
      Friday: "09:00-21:00",
      Saturday: "10:00-18:00",
      Sunday: "Closed",
    },
    photos: mockPhotos.filter((p) => p.business_id === "business_003"),
  },
  {
    business_id: "business_004",
    name: "Hotel Plaza Central",
    address: "Plaza Mayor 1",
    city: "Madrid",
    state: "MD",
    postal_code: "28012",
    latitude: 40.4153,
    longitude: -3.7074,
    stars: 4.0,
    review_count: 210,
    is_open: 1,
    attributes: {
      BusinessAcceptsCreditCards: true,
      WiFi: "free",
      ParkingAvailable: true,
    },
    categories: ["Hoteles", "Alojamiento", "Turismo"],
    hours: {
      Monday: "00:00-23:59",
      Tuesday: "00:00-23:59",
      Wednesday: "00:00-23:59",
      Thursday: "00:00-23:59",
      Friday: "00:00-23:59",
      Saturday: "00:00-23:59",
      Sunday: "00:00-23:59",
    },
    photos: mockPhotos.filter((p) => p.business_id === "business_004"),
  },
  {
    business_id: "business_005",
    name: "Gimnasio Fitness Plus",
    address: "Avenida Deportiva 34",
    city: "Barcelona",
    state: "CT",
    postal_code: "08005",
    latitude: 41.3948,
    longitude: 2.1975,
    stars: 3.8,
    review_count: 76,
    is_open: 1,
    attributes: {
      BusinessAcceptsCreditCards: true,
      BikeParking: true,
      GoodForKids: false,
    },
    categories: ["Gimnasios", "Fitness", "Salud"],
    hours: {
      Monday: "07:00-22:00",
      Tuesday: "07:00-22:00",
      Wednesday: "07:00-22:00",
      Thursday: "07:00-22:00",
      Friday: "07:00-22:00",
      Saturday: "09:00-20:00",
      Sunday: "09:00-14:00",
    },
    photos: mockPhotos.filter((p) => p.business_id === "business_005"),
  },
]

// Mock de reseñas
export const mockReviews: Review[] = [
  {
    review_id: "review_001",
    user_id: "user_001",
    business_id: "business_001",
    stars: 5,
    date: "2022-05-15",
    text: "Excelente experiencia gastronómica. La comida estaba deliciosa y el servicio fue impecable. Definitivamente volveré pronto.",
    useful: 8,
    funny: 2,
    cool: 3,
    user: mockUsers[0],
  },
  {
    review_id: "review_002",
    user_id: "user_002",
    business_id: "business_001",
    stars: 4,
    date: "2022-06-20",
    text: "Muy buena relación calidad-precio. Los platos son abundantes y sabrosos. El ambiente es agradable aunque un poco ruidoso en horas punta.",
    useful: 5,
    funny: 1,
    cool: 2,
    user: mockUsers[1],
  },
  {
    review_id: "review_003",
    user_id: "user_003",
    business_id: "business_001",
    stars: 3,
    date: "2022-07-10",
    text: "La comida estaba bien, pero el servicio fue lento. Tuvimos que esperar más de 30 minutos para que nos atendieran. El local es bonito y la ubicación excelente.",
    useful: 12,
    funny: 0,
    cool: 1,
    user: mockUsers[2],
  },
  {
    review_id: "review_004",
    user_id: "user_001",
    business_id: "business_002",
    stars: 5,
    date: "2022-04-05",
    text: "El mejor café de la ciudad. El ambiente es perfecto para trabajar o leer un libro. El personal es muy amable y los pasteles son deliciosos.",
    useful: 15,
    funny: 3,
    cool: 7,
    user: mockUsers[0],
  },
  {
    review_id: "review_005",
    user_id: "user_002",
    business_id: "business_002",
    stars: 4,
    date: "2022-05-12",
    text: "Buen lugar para desayunar. Los precios son razonables y la calidad es buena. La conexión WiFi funciona bien, lo que lo hace ideal para trabajar.",
    useful: 6,
    funny: 1,
    cool: 2,
    user: mockUsers[1],
  },
  {
    review_id: "review_006",
    user_id: "user_003",
    business_id: "business_002",
    stars: 4,
    date: "2022-06-18",
    text: "Me encanta este café. El brunch de fin de semana es espectacular. La terraza es muy agradable en días soleados.",
    useful: 8,
    funny: 2,
    cool: 3,
    user: mockUsers[2],
  },
  {
    review_id: "review_007",
    user_id: "user_001",
    business_id: "business_003",
    stars: 5,
    date: "2022-03-10",
    text: "Excelente espacio de coworking. Las instalaciones son modernas y cómodas. La conexión a internet es rápida y estable. El personal es muy profesional.",
    useful: 10,
    funny: 0,
    cool: 5,
    user: mockUsers[0],
  },
  {
    review_id: "review_008",
    user_id: "user_002",
    business_id: "business_003",
    stars: 4,
    date: "2022-04-22",
    text: "Buen lugar para trabajar. Las salas de reuniones están bien equipadas. El único inconveniente es que a veces hay demasiado ruido en las áreas comunes.",
    useful: 7,
    funny: 1,
    cool: 2,
    user: mockUsers[1],
  },
  {
    review_id: "review_009",
    user_id: "user_003",
    business_id: "business_003",
    stars: 5,
    date: "2022-05-30",
    text: "El mejor espacio de coworking que he visitado. La comunidad es muy colaborativa y se organizan eventos interesantes. Totalmente recomendable.",
    useful: 12,
    funny: 2,
    cool: 6,
    user: mockUsers[2],
  },
]

// Mock de recomendaciones
export const mockRecommendations: Recommendation[] = [
  {
    id: "user_001_rec_001",
    business: mockBusinesses[0],
    score: 0.92,
    explanation: {
      factors: [
        {
          name: "Similitud de Preferencias",
          weight: 0.6,
          description: "Basado en tus reseñas previas de restaurantes españoles",
        },
        {
          name: "Popularidad",
          weight: 0.3,
          description: "Este negocio tiene una alta calificación y muchas reseñas positivas",
        },
        {
          name: "Ubicación",
          weight: 0.1,
          description: "Cercano a lugares que has visitado anteriormente",
        },
      ],
      text: "Te recomendamos El Rincón Gourmet porque has mostrado interés en restaurantes españoles con buenas reseñas y está ubicado en una zona que frecuentas.",
    },
    userFeedback: true,
  },
  {
    id: "user_001_rec_002",
    business: mockBusinesses[1],
    score: 0.87,
    explanation: {
      factors: [
        {
          name: "Historial de Visitas",
          weight: 0.5,
          description: "Has visitado cafeterías similares en el pasado",
        },
        {
          name: "Recomendaciones de Amigos",
          weight: 0.3,
          description: "Amigos en tu red han valorado positivamente este lugar",
        },
        {
          name: "Tendencias",
          weight: 0.2,
          description: "Este tipo de cafeterías están ganando popularidad entre usuarios con gustos similares",
        },
      ],
      text: "Café del Arte coincide con tu perfil de visitas a cafeterías con buen ambiente para trabajar y ha sido bien valorado por personas con gustos similares a los tuyos.",
    },
    userFeedback: null,
  },
  {
    id: "user_001_rec_003",
    business: mockBusinesses[2],
    score: 0.78,
    explanation: {
      factors: [
        {
          name: "Perfil Profesional",
          weight: 0.7,
          description: "Basado en tu perfil profesional y necesidades de trabajo",
        },
        {
          name: "Calificaciones",
          weight: 0.2,
          description: "Este espacio tiene excelentes calificaciones en servicios y comodidades",
        },
        {
          name: "Novedad",
          weight: 0.1,
          description: "Es un lugar nuevo que podría interesarte conocer",
        },
      ],
      text: "Espacio Coworking Innovación se ajusta a tu perfil profesional y ofrece servicios que podrían ser útiles para tu trabajo, con excelentes calificaciones de otros usuarios.",
    },
    userFeedback: false,
  },
  {
    id: "user_002_rec_001",
    business: mockBusinesses[3],
    score: 0.89,
    explanation: {
      factors: [
        {
          name: "Historial de Viajes",
          weight: 0.6,
          description: "Basado en tus patrones de viaje y estancias previas",
        },
        {
          name: "Preferencias de Comodidades",
          weight: 0.3,
          description: "Este hotel ofrece comodidades que has valorado positivamente",
        },
        {
          name: "Ubicación",
          weight: 0.1,
          description: "Ubicado en una zona que has visitado anteriormente",
        },
      ],
      text: "Hotel Plaza Central coincide con tus preferencias de alojamiento en viajes anteriores y está ubicado en una zona céntrica que has visitado antes.",
    },
    userFeedback: null,
  },
  {
    id: "user_002_rec_002",
    business: mockBusinesses[4],
    score: 0.76,
    explanation: {
      factors: [
        {
          name: "Intereses de Fitness",
          weight: 0.5,
          description: "Basado en tu interés en actividades físicas y bienestar",
        },
        {
          name: "Ubicación",
          weight: 0.3,
          description: "Cercano a lugares que frecuentas habitualmente",
        },
        {
          name: "Promociones",
          weight: 0.2,
          description: "Actualmente tiene ofertas especiales que podrían interesarte",
        },
      ],
      text: "Gimnasio Fitness Plus se alinea con tus intereses en actividades físicas y está ubicado cerca de otros lugares que frecuentas, además de tener promociones especiales actualmente.",
    },
    userFeedback: true,
  },
  {
    id: "user_002_rec_003",
    business: mockBusinesses[0],
    score: 0.72,
    explanation: {
      factors: [
        {
          name: "Preferencias Gastronómicas",
          weight: 0.6,
          description: "Basado en tus preferencias culinarias previas",
        },
        {
          name: "Ocasiones Especiales",
          weight: 0.3,
          description: "Ideal para celebraciones según tu historial",
        },
        {
          name: "Novedad",
          weight: 0.1,
          description: "Ofrece platos nuevos que podrían interesarte",
        },
      ],
      text: "El Rincón Gourmet ofrece una experiencia gastronómica que coincide con tus preferencias culinarias y es ideal para ocasiones especiales como las que has celebrado anteriormente.",
    },
    userFeedback: null,
  },
  {
    id: "user_003_rec_001",
    business: mockBusinesses[1],
    score: 0.94,
    explanation: {
      factors: [
        {
          name: "Hábitos Matutinos",
          weight: 0.5,
          description: "Coincide con tus hábitos de desayuno y mañana",
        },
        {
          name: "Ambiente",
          weight: 0.3,
          description: "El ambiente tranquilo se ajusta a tus preferencias",
        },
        {
          name: "Calidad",
          weight: 0.2,
          description: "Alta calidad en productos que sueles consumir",
        },
      ],
      text: "Café del Arte se alinea perfectamente con tus hábitos matutinos y preferencias de ambiente tranquilo, ofreciendo productos de alta calidad similares a los que sueles consumir.",
    },
    userFeedback: true,
  },
  {
    id: "user_003_rec_002",
    business: mockBusinesses[2],
    score: 0.81,
    explanation: {
      factors: [
        {
          name: "Perfil Laboral",
          weight: 0.6,
          description: "Basado en tu perfil profesional y necesidades de trabajo",
        },
        {
          name: "Networking",
          weight: 0.3,
          description: "Oportunidades de networking con profesionales similares",
        },
        {
          name: "Servicios",
          weight: 0.1,
          description: "Servicios adicionales que podrían ser útiles para ti",
        },
      ],
      text: "Espacio Coworking Innovación ofrece un entorno de trabajo que se ajusta a tu perfil profesional, con oportunidades de networking y servicios adicionales que podrían beneficiarte.",
    },
    userFeedback: null,
  },
  {
    id: "user_003_rec_003",
    business: mockBusinesses[4],
    score: 0.68,
    explanation: {
      factors: [
        {
          name: "Interés en Bienestar",
          weight: 0.7,
          description: "Basado en tu interés reciente en actividades de bienestar",
        },
        {
          name: "Horarios",
          weight: 0.2,
          description: "Horarios compatibles con tu rutina diaria",
        },
        {
          name: "Instalaciones",
          weight: 0.1,
          description: "Instalaciones modernas que podrían interesarte",
        },
      ],
      text: "Gimnasio Fitness Plus ofrece actividades de bienestar que coinciden con tus intereses recientes, con horarios compatibles con tu rutina e instalaciones modernas.",
    },
    userFeedback: false,
  },
]

// Mock de métricas de experimentos
export const mockExperimentMetrics: ExperimentMetrics = {
  algorithms: [
    {
      name: "Filtrado Colaborativo",
      precision: 0.82,
      recall: 0.75,
      f1Score: 0.78,
      rmse: 0.95,
    },
    {
      name: "Basado en Contenido",
      precision: 0.78,
      recall: 0.81,
      f1Score: 0.79,
      rmse: 1.05,
    },
    {
      name: "Híbrido (Ponderado)",
      precision: 0.85,
      recall: 0.83,
      f1Score: 0.84,
      rmse: 0.87,
    },
    {
      name: "Híbrido (Cascada)",
      precision: 0.83,
      recall: 0.8,
      f1Score: 0.81,
      rmse: 0.92,
    },
    {
      name: "Basado en Conocimiento",
      precision: 0.76,
      recall: 0.72,
      f1Score: 0.74,
      rmse: 1.12,
    },
  ],
  performanceOverTime: [
    {
      epoch: 1,
      precision: 0.65,
      recall: 0.6,
      f1Score: 0.62,
    },
    {
      epoch: 2,
      precision: 0.7,
      recall: 0.68,
      f1Score: 0.69,
    },
    {
      epoch: 3,
      precision: 0.75,
      recall: 0.72,
      f1Score: 0.73,
    },
    {
      epoch: 4,
      precision: 0.79,
      recall: 0.76,
      f1Score: 0.77,
    },
    {
      epoch: 5,
      precision: 0.82,
      recall: 0.79,
      f1Score: 0.8,
    },
    {
      epoch: 6,
      precision: 0.84,
      recall: 0.81,
      f1Score: 0.82,
    },
    {
      epoch: 7,
      precision: 0.85,
      recall: 0.83,
      f1Score: 0.84,
    },
  ],
  categoryDistribution: [
    {
      category: "Restaurantes",
      value: 35,
    },
    {
      category: "Cafeterías",
      value: 25,
    },
    {
      category: "Hoteles",
      value: 15,
    },
    {
      category: "Servicios",
      value: 10,
    },
    {
      category: "Ocio",
      value: 15,
    },
  ],
}
